### ISSUE TITLE
Feature request: Additional config file inclusion

### ISSUE THREAD

**Issue by rarog** [riddlestone/brokkr-console#2]
Currently application and development are included.
By adding an additional optional config file inclusion it would be possible to override some of the basic settings only for console application instead of for the global and normal scope.

For example I had a module in the past, that was based on zfcampus/zf-console, where I disabled config and module cache hardcoded in my bin/command.php file. Of course I could just copy your bin/broker.php to extend it with my functionality, but including a second additional config perhaps even before development-config would allow me to do this without additional mangling or copying and just relying on your module.

**Comment by ariddlestone** [comment]
That's a good idea - something like 70341d3f81421db449546eeda4b5037d8a8fe830?

**Comment by rarog** [comment]
> 
> 
> That's a good idea - something like [70341d3](https://github.com/riddlestone/brokkr-console/commit/70341d3f81421db449546eeda4b5037d8a8fe830)?

Absolutely, that simple and sufficient!

**Comment by ariddlestone** [comment]
Now available in v1.2.0
